### ISSUE TITLE
Unexpected Pagination Columns in Trino Query Results

### ISSUE THREAD

**Issue by ofirNakdai** [nineinchnick/trino-openapi#137]
## Description

I'm running a POC on integrating Trino with an OpenAPI connector. The API implements pagination for handling large tables. I added a `x-pagination` section to the `spec.yaml` file, intending to enable proper pagination behavior. However, when querying a table, Trino returns the pagination metadata (e.g., `total`, `pages`, `size`, `page`) as additional columns alongside the actual table data.

This behavior is unexpected and problematic as the pagination details are not part of the desired query output.

## Environment
* **Trino Version:** 464, 453
* **OpenAPI version:** 1.67, 1.60

## Example `x-pagination` Section (`spec.yaml`)
```yaml
"x-pagination": {
          "pageParam": "page",
          "limitParam": "size",
          "resultsPath": "$response.body#/items",
          "totalResultsPath": "$response.body#/total"
}
```

## OpenAPI configuration (`.properties`):
```
connector.name=openapi
spec-location=http://host.docker.internal:8000/spec
base-uri=http://host.docker.internal:8000
authentication.type=http
authentication.scheme=basic
authentication.username=****
authentication.password=****
```

## Trino response Example
Where `total`, `pages`, `size`, `page` are not part of the actual data

![image](https://github.com/user-attachments/assets/e4af94f0-07a1-4372-97f6-f5d9c08ce4af)
