### ISSUE TITLE
Don't require base URI if spec includes servers

### ISSUE THREAD

**Issue by nineinchnick** [nineinchnick/trino-openapi#51]
Some specs include a set of servers:
```
paths:
  /v1/forecast:
    servers:
      - url: https://api.open-meteo.com
```

Looks like this can be used instead of the base URI configuration option, making the spec location the single required option.
